### PR TITLE
Gh pages updates and feedback

### PR DESCRIPTION
**Pull request by makeusabrew**
Submitting a PR more for visibility's sake than anything else 🙂 

* Updates copyright year
* Gives a nod to contributors ❤️ 
* Updates `makeusabrew` GitHub URLs to `bootboxjs`
* Updates some old personal URLs relating to me
* Adds in-page feedback on current docs (full disclosure: this uses another project of mine)
* Adds a very basic docs readme

### CODE REVIEW

**Comment by tiesont** [comment]
@makeusabrew The gh-pages content is the generated output from https://github.com/tiesont/bootboxdocs - what I'd like to do is update the repo to use some version of that (or replace it with something newer, if someone wants to go that route). I also didn't realize, when I pushed it to "production", that the current site pretty much looks like crap on mobile (I _really_ thought I tested that, but guess not).

It also seems like Github really wants us to use a `/docs` directory in the master/main branch, which would let us use the updated build tooling around site publishing.

Maybe we enable the Discussions tab and start a topic about this?

**Comment by aadrian** [comment]
> Maybe we enable the Discussions tab and start a topic about this?

+1

Formatting of code samples seems broken on most examples on the main site.

**Comment by tiesont** [comment]
> > Maybe we enable the Discussions tab and start a topic about this?
> 
> +1
> 
> Formatting of code samples seems broken on most examples on the main site.

Yeah, I suspect @makeusabrew is using different line endings and whatnot than me. I _thought_ that was accounted for, but I seem to have missed some stuff in my desire/haste to push updates to account for v6.

**Comment by makeusabrew** [comment]
Sorry folks, I've nerfed my GitHub notification settings due to one or two repositories being way too chatty and now seem to be getting no emails at all. Massive apologies for messing up the examples formatting.

I'm up for enabling discussions and planning a proper way forward for the docs. GH pages definitely looks like the legacy way to do things. On the plus side after a lot of faff the site is finally now served over HTTPS - only a few years late on that one ;)

**Pull request merged**
